# -*- coding: utf-8 -*-
"""
Generates Documentation/dax_measure_dictionary.md from the measure specification
(Python/model_measures.py), merged with the grand-total value of every measure as
measured in the live model by Validation/reconcile_measures.ps1
(Validation/measure_values.csv). Values are never typed by hand.

Usage:  python Python/03_generate_measure_dictionary.py
"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "Python"))
from model_measures import MEASURES  # noqa: E402

OUT = ROOT / "Documentation" / "dax_measure_dictionary.md"
VALUES = ROOT / "Validation" / "measure_values.csv"


def fmt_value(raw, fmt):
    if raw in (None, ""):
        return "(blank)"
    try:
        v = float(raw)
    except ValueError:
        return raw
    if fmt and "%" in fmt:
        return f"{v:.2%}"
    if fmt and "$" in fmt:
        return f"${v:,.2f}" if abs(v) < 1000 else f"${v:,.0f}"
    if v.is_integer():
        return f"{int(v):,}"
    return f"{v:,.4f}"


def main():
    values = {}
    if VALUES.exists():
        with VALUES.open(encoding="utf-8-sig") as f:
            values = {r["Measure"]: r["Value"] for r in csv.DictReader(f)}

    folders = {}
    for m in MEASURES:
        folders.setdefault(m["folder"], []).append(m)

    L = ["# DAX Measure Dictionary - Omnichannel Marketing Attribution", "",
         "Generated by `Python/03_generate_measure_dictionary.py` from `Python/model_measures.py`. "
         "**Value (all data)** is each measure at the grand total, measured in the live Power BI model by "
         "`Validation/reconcile_measures.ps1` - not typed by hand. Attributed measures use the default model "
         "(Position-Based). Money is USD at planning FX rates. The data is synthetic.", "",
         f"**{len(MEASURES)} measures in {len(folders)} folders.**", ""]
    for folder, ms in folders.items():
        L += [f"## {folder}", "", "| Measure | Value (all data) | Description |", "|---|---|---|"]
        for m in ms:
            L.append(f"| {m['name']} | {fmt_value(values.get(m['name']), m['fmt'])} | {m['desc']} |")
        L.append("")
        for m in ms:
            L += [f"<details><summary><code>{m['name']}</code></summary>", "", "```dax", m["dax"].strip("\n"), "```",
                  "", "</details>", ""]
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(MEASURES)} measures, "
          f"{sum(1 for m in MEASURES if m['name'] in values)} with measured values")


if __name__ == "__main__":
    main()
