/*=============================================================================
  08_validation.sql
  -----------------------------------------------------------------------------
  Project : Enterprise Supply Chain Control Tower
  Phase   : 3 - SQL Data Platform
  Purpose : Prove the SQL layer is trustworthy before Power BI is pointed at it.

  Every check writes a row into #Results with an expected value, the observed
  value and a verdict. The script ends with a single gate: if any check fails,
  it says so explicitly rather than leaving a reader to scan the detail.

  The expected source counts are the ones produced independently by
  Python/01_data_audit.py reading the CSVs with pandas. Using an independent
  count matters - reconciling the load against itself would prove nothing.

  Read-only. Safe to run at any time.
=============================================================================*/

USE SupplyChainBI;
GO
SET NOCOUNT ON;
GO

DROP TABLE IF EXISTS #Results;
CREATE TABLE #Results
(
    Seq       int IDENTITY(1,1),
    Section   varchar(40)   NOT NULL,
    CheckName varchar(120)  NOT NULL,
    Expected  varchar(60)   NOT NULL,
    Actual    varchar(60)   NOT NULL,
    [Status]  varchar(6)    NOT NULL,
    Note      nvarchar(300) NULL
);

DECLARE @AsOf date = (SELECT TRY_CONVERT(date, ConfigValue, 23)
                      FROM dbo.ModelConfig WHERE ConfigKey = 'AsOfDate');

/*=============================================================================
  SECTION 1 - Row count reconciliation: source -> stg -> dbo -> analytics
=============================================================================*/
DECLARE @Expected TABLE
(
    Entity     varchar(40) PRIMARY KEY,
    SourceRows int,
    StgTable   sysname,
    DboTable   sysname,
    ViewName   sysname,
    Note       nvarchar(200)
);

INSERT INTO @Expected VALUES
 ('DimDate',              1704, 'stg.DimDate',               'dbo.DimDate',               'analytics.vw_DimDate',
  N'dbo intentionally differs: calendar REGENERATED to 2027-06-30, not imported.'),
 ('DimProduct',           1000, 'stg.DimProduct',            'dbo.DimProduct',            'analytics.vw_DimProduct',            NULL),
 ('DimSupplier',           120, 'stg.DimSupplier',           'dbo.DimSupplier',           'analytics.vw_DimSupplier',           NULL),
 ('DimWarehouse',            6, 'stg.DimWarehouse',          'dbo.DimWarehouse',          'analytics.vw_DimWarehouse',          NULL),
 ('FactSalesOrders',     80000, 'stg.FactSalesOrders',       'dbo.FactSalesOrders',       'analytics.vw_SalesOrders',           NULL),
 ('FactPurchaseOrders',  25000, 'stg.FactPurchaseOrders',    'dbo.FactPurchaseOrders',    'analytics.vw_PurchaseOrders',        NULL),
 ('FactShipments',       80000, 'stg.FactShipments',         'dbo.FactShipments',         'analytics.vw_Shipments',             NULL),
 ('FactWeeklyDemand',   315000, 'stg.FactWeeklyDemand',      'dbo.FactWeeklyDemand',      'analytics.vw_WeeklyDemand',          NULL),
 ('FactInventorySnapshot',315000,'stg.FactInventorySnapshot','dbo.FactInventorySnapshot', 'analytics.vw_InventorySnapshot',     NULL),
 ('SecurityUserAccess',      7, 'stg.SecurityUserAccess',    'dbo.SecurityUserAccess',    'analytics.vw_SecurityUserAccess',    NULL);

DROP TABLE IF EXISTS #Counts;
CREATE TABLE #Counts (Entity varchar(40), StgRows int, DboRows int, ViewRows int);

DECLARE @Entity varchar(40), @Stg sysname, @Dbo sysname, @Vw sysname, @Sql nvarchar(max);
DECLARE cur CURSOR LOCAL FAST_FORWARD FOR SELECT Entity, StgTable, DboTable, ViewName FROM @Expected;
OPEN cur;
FETCH NEXT FROM cur INTO @Entity, @Stg, @Dbo, @Vw;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @Sql = N'INSERT INTO #Counts (Entity, StgRows, DboRows, ViewRows)
                 SELECT @e,
                        (SELECT COUNT(*) FROM ' + @Stg + N'),
                        (SELECT COUNT(*) FROM ' + @Dbo + N'),
                        (SELECT COUNT(*) FROM ' + @Vw  + N');';
    EXEC sys.sp_executesql @Sql, N'@e varchar(40)', @e = @Entity;
    FETCH NEXT FROM cur INTO @Entity, @Stg, @Dbo, @Vw;
END
CLOSE cur; DEALLOCATE cur;

-- Source -> staging must always match exactly.
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Reconciliation',
       CONCAT('Source -> stg : ', e.Entity),
       CAST(e.SourceRows AS varchar(20)),
       CAST(c.StgRows AS varchar(20)),
       CASE WHEN e.SourceRows = c.StgRows THEN 'PASS' ELSE 'FAIL' END,
       NULL
FROM @Expected AS e JOIN #Counts AS c ON c.Entity = e.Entity;

-- staging -> dbo must match, except DimDate which is regenerated by design.
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Reconciliation',
       CONCAT('stg -> dbo : ', e.Entity),
       CASE WHEN e.Entity = 'DimDate' THEN '2007 (regenerated)' ELSE CAST(c.StgRows AS varchar(20)) END,
       CAST(c.DboRows AS varchar(20)),
       CASE WHEN e.Entity = 'DimDate'
            THEN CASE WHEN c.DboRows = 2007 THEN 'PASS' ELSE 'FAIL' END
            ELSE CASE WHEN c.StgRows = c.DboRows THEN 'PASS' ELSE 'FAIL' END
       END,
       e.Note
FROM @Expected AS e JOIN #Counts AS c ON c.Entity = e.Entity;

-- dbo -> analytics view must match: a view must never lose or multiply facts.
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Reconciliation',
       CONCAT('dbo -> view : ', e.Entity),
       CAST(c.DboRows AS varchar(20)),
       CAST(c.ViewRows AS varchar(20)),
       CASE WHEN c.DboRows = c.ViewRows THEN 'PASS' ELSE 'FAIL' END,
       CASE WHEN e.Entity = 'FactShipments'
            THEN N'Critical: ProductID is resolved by joining FactSalesOrders. Any drift means the join multiplied or dropped rows.'
            WHEN e.Entity = 'FactPurchaseOrders'
            THEN N'Joins DimProduct to derive purchase price variance.'
       END
FROM @Expected AS e JOIN #Counts AS c ON c.Entity = e.Entity;

/*=============================================================================
  SECTION 2 - Primary key uniqueness
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Primary keys', 'dbo.DimProduct (ProductID)', '0 duplicates',
       CAST(COUNT(*) AS varchar(20)) + ' duplicates',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT ProductID FROM dbo.DimProduct GROUP BY ProductID HAVING COUNT(*) > 1) AS x;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Primary keys', 'dbo.FactSalesOrders (SalesOrderID)', '0 duplicates',
       CAST(COUNT(*) AS varchar(20)) + ' duplicates',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT SalesOrderID FROM dbo.FactSalesOrders GROUP BY SalesOrderID HAVING COUNT(*) > 1) AS x;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Primary keys', 'dbo.FactWeeklyDemand (WeekStart+Product+Warehouse)', '0 duplicates',
       CAST(COUNT(*) AS varchar(20)) + ' duplicates',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT WeekStart, ProductID, WarehouseID FROM dbo.FactWeeklyDemand
      GROUP BY WeekStart, ProductID, WarehouseID HAVING COUNT(*) > 1) AS x;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Primary keys', 'dbo.FactInventorySnapshot (Snapshot+Product+Warehouse)', '0 duplicates',
       CAST(COUNT(*) AS varchar(20)) + ' duplicates',
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM (SELECT SnapshotDate, ProductID, WarehouseID FROM dbo.FactInventorySnapshot
      GROUP BY SnapshotDate, ProductID, WarehouseID HAVING COUNT(*) > 1) AS x;

/*=============================================================================
  SECTION 3 - Referential integrity
  ---------------------------------------------------------------------------
  The constraints already enforce this, so the meaningful test is whether the
  engine TRUSTS them. An untrusted constraint was created WITH NOCHECK and
  guarantees nothing about existing rows.
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Referential integrity', 'Foreign keys declared and trusted', '25 trusted',
       CONCAT(COUNT(*), ' declared, ',
              SUM(CASE WHEN is_not_trusted = 0 THEN 1 ELSE 0 END), ' trusted'),
       CASE WHEN COUNT(*) = SUM(CASE WHEN is_not_trusted = 0 THEN 1 ELSE 0 END)
                 AND COUNT(*) >= 25 THEN 'PASS' ELSE 'FAIL' END,
       N'Trusted means SQL Server validated every existing row when the constraint was created.'
FROM sys.foreign_keys WHERE SCHEMA_NAME(schema_id) = 'dbo';

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Referential integrity', 'Check constraints trusted', 'all trusted',
       CONCAT(COUNT(*), ' declared, ',
              SUM(CASE WHEN is_not_trusted = 0 THEN 1 ELSE 0 END), ' trusted'),
       CASE WHEN COUNT(*) = SUM(CASE WHEN is_not_trusted = 0 THEN 1 ELSE 0 END)
            THEN 'PASS' ELSE 'FAIL' END
FROM sys.check_constraints WHERE SCHEMA_NAME(schema_id) = 'dbo';

-- Explicit orphan hunt, independent of the constraints.
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Referential integrity', 'Shipments without a parent sales order', '0',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactShipments AS sh
WHERE NOT EXISTS (SELECT 1 FROM dbo.FactSalesOrders AS so WHERE so.SalesOrderID = sh.SalesOrderID);

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Referential integrity', 'Fact dates outside the calendar', '0',
       CAST(SUM(cnt) AS varchar(20)),
       CASE WHEN SUM(cnt) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'This is the defect the supplied calendar had: 1,938 rows reached beyond 2026-08-31.'
FROM (
    SELECT cnt = COUNT(*) FROM dbo.FactSalesOrders s
     WHERE NOT EXISTS (SELECT 1 FROM dbo.DimDate d WHERE d.[Date] = s.OrderDate)
        OR NOT EXISTS (SELECT 1 FROM dbo.DimDate d WHERE d.[Date] = s.PromisedDeliveryDate)
    UNION ALL
    SELECT COUNT(*) FROM dbo.FactSalesOrders s
     WHERE s.ActualDeliveryDate IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM dbo.DimDate d WHERE d.[Date] = s.ActualDeliveryDate)
    UNION ALL
    SELECT COUNT(*) FROM dbo.FactSalesOrders s
     WHERE s.ScheduledDeliveryDate IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM dbo.DimDate d WHERE d.[Date] = s.ScheduledDeliveryDate)
    UNION ALL
    SELECT COUNT(*) FROM dbo.FactPurchaseOrders p
     WHERE p.ScheduledReceiptDate IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM dbo.DimDate d WHERE d.[Date] = p.ScheduledReceiptDate)
    UNION ALL
    SELECT COUNT(*) FROM dbo.FactShipments sh
     WHERE sh.ScheduledDeliveryDate IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM dbo.DimDate d WHERE d.[Date] = sh.ScheduledDeliveryDate)
) AS x;

/*=============================================================================
  SECTION 4 - Sales order date logic
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Sales date logic', 'Actual and Scheduled are mutually exclusive', '0 rows with both',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'The invariant the whole split exists to create: neither column can ever be ambiguous.'
FROM dbo.FactSalesOrders
WHERE ActualDeliveryDate IS NOT NULL AND ScheduledDeliveryDate IS NOT NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Sales date logic', 'Every order has exactly one delivery date', '0 rows with neither',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactSalesOrders
WHERE ActualDeliveryDate IS NULL AND ScheduledDeliveryDate IS NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Sales date logic', 'Open orders carry no ActualDeliveryDate', '0',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'435 open orders in the source carried a future date in the actual-delivery column.'
FROM dbo.FactSalesOrders WHERE IsOpenOrder = 1 AND ActualDeliveryDate IS NOT NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Sales date logic', 'Open orders have a ScheduledDeliveryDate', '435',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 435 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactSalesOrders WHERE IsOpenOrder = 1 AND ScheduledDeliveryDate IS NOT NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Sales date logic', 'Derived IsDelivered agrees with source OrderStatus', '0 disagreements',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'Completion is derived from the date; this proves the source status label agrees.'
FROM dbo.FactSalesOrders
WHERE (OrderStatus = 'Delivered' AND IsDelivered = 0)
   OR (OrderStatus <> 'Delivered' AND IsDelivered = 1);

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Sales date logic', 'No delay recorded against an undelivered order', '0',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'An order not yet due has no delay. Zero would understate lateness; a negative would invent earliness.'
FROM dbo.FactSalesOrders WHERE IsOpenOrder = 1 AND DeliveryDelayDays IS NOT NULL;

/*=============================================================================
  SECTION 5 - Purchase order date logic
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Purchase date logic', 'Actual and Scheduled are mutually exclusive', '0 rows with both',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactPurchaseOrders
WHERE ActualReceiptDate IS NOT NULL AND ScheduledReceiptDate IS NOT NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Purchase date logic', 'Open POs carry no ActualReceiptDate', '0',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactPurchaseOrders WHERE IsOpenPO = 1 AND ActualReceiptDate IS NOT NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Purchase date logic', 'Open POs have a ScheduledReceiptDate', '368',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 368 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactPurchaseOrders WHERE IsOpenPO = 1 AND ScheduledReceiptDate IS NOT NULL;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Purchase date logic', 'Derived IsReceived agrees with source Status', '0 disagreements',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactPurchaseOrders
WHERE ([Status] = 'Received' AND IsReceived = 0)
   OR ([Status] <> 'Received' AND IsReceived = 1);

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Purchase date logic', 'No lead time recorded against an open PO', '0',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'Supplier lead time is only measurable once goods are actually received.'
FROM dbo.FactPurchaseOrders WHERE IsOpenPO = 1 AND ActualLeadTimeDays IS NOT NULL;

/*=============================================================================
  SECTION 6 - As-of date logic
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'As-of logic', 'No actual date lies after the as-of date', '0',
       CAST(SUM(cnt) AS varchar(20)),
       CASE WHEN SUM(cnt) = 0 THEN 'PASS' ELSE 'FAIL' END,
       CONCAT(N'An event cannot have happened after the extract was taken. As-of = ', @AsOf, '.')
FROM (
    SELECT cnt = COUNT(*) FROM dbo.FactSalesOrders     WHERE ActualDeliveryDate > @AsOf
    UNION ALL SELECT COUNT(*) FROM dbo.FactPurchaseOrders WHERE ActualReceiptDate  > @AsOf
    UNION ALL SELECT COUNT(*) FROM dbo.FactShipments      WHERE ActualDeliveryDate > @AsOf
) AS x;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'As-of logic', 'No scheduled date lies on or before the as-of date', '0',
       CAST(SUM(cnt) AS varchar(20)),
       CASE WHEN SUM(cnt) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'A date in the past is not a schedule; it is history.'
FROM (
    SELECT cnt = COUNT(*) FROM dbo.FactSalesOrders     WHERE ScheduledDeliveryDate <= @AsOf
    UNION ALL SELECT COUNT(*) FROM dbo.FactPurchaseOrders WHERE ScheduledReceiptDate  <= @AsOf
    UNION ALL SELECT COUNT(*) FROM dbo.FactShipments      WHERE ScheduledDeliveryDate <= @AsOf
) AS x;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'As-of logic', 'In-flight orders are excludable from OTIF', '435 open / 79565 due',
       CONCAT(SUM(CAST(IsOpenOrder AS int)), ' open / ', SUM(CAST(IsDelivered AS int)), ' due'),
       CASE WHEN SUM(CAST(IsOpenOrder AS int)) = 435
                 AND SUM(CAST(IsDelivered AS int)) = 79565 THEN 'PASS' ELSE 'FAIL' END,
       N'OTIF must be measured only over orders that were actually due by the as-of date.'
FROM dbo.FactSalesOrders;

/*=============================================================================
  SECTION 7 - Date dimension
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Date dimension', 'Calendar span', '2022-01-01 to 2027-06-30',
       CONCAT(MIN([Date]), ' to ', MAX([Date])),
       CASE WHEN MIN([Date]) = '2022-01-01' AND MAX([Date]) = '2027-06-30'
            THEN 'PASS' ELSE 'FAIL' END
FROM dbo.DimDate;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Date dimension', 'Contiguous with no gaps or duplicates', '2007',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = DATEDIFF(day, MIN([Date]), MAX([Date])) + 1
            THEN 'PASS' ELSE 'FAIL' END,
       N'Row count must equal the day span, or time intelligence will silently misbehave.'
FROM dbo.DimDate;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Date dimension', 'Financial year mapping (July to June)', '0 errors',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'July 2026 through June 2027 must all resolve to FY27.'
FROM dbo.DimDate
WHERE FinancialYearNumber <> [Year] + CASE WHEN MonthNumber >= 7 THEN 1 ELSE 0 END
   OR FinancialYear <> CONCAT('FY', RIGHT(CAST(FinancialYearNumber AS varchar(4)), 2));

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Date dimension', 'ISO week matches DATEPART(ISO_WEEK)', '0 errors',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'Independent check of the hand-rolled ISO logic against the engine built-in.'
FROM dbo.DimDate WHERE ISOWeek <> DATEPART(ISO_WEEK, [Date]);

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Date dimension', 'ISO week 53 present at the 2026/27 boundary', '>0 days',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
       N'ISO 2026 has 53 weeks. The supplied calendar never reached it; the generated one must.'
FROM dbo.DimDate WHERE ISOWeek = 53;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Date dimension', 'WeekStartDate always falls on a Monday', '0 errors',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.DimDate
WHERE (DATEDIFF(day, '1900-01-01', WeekStartDate) % 7) <> 0;

/*=============================================================================
  SECTION 8 - Inventory reconciliation
  ---------------------------------------------------------------------------
  InventoryValue was dropped from dbo on the basis that it is exactly
  derivable. That claim is only safe if it is re-proved against the raw value
  still held in staging.
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Inventory', 'InventoryValue = OnHandUnits x UnitCost', '0 deviations',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'Justifies excluding the column from dbo: DAX can rebuild it exactly from DimProduct.'
FROM      stg.FactInventorySnapshot AS s
JOIN      dbo.DimProduct            AS p ON p.ProductID = LTRIM(RTRIM(s.ProductID))
WHERE ABS(TRY_CONVERT(decimal(18,2), s.InventoryValue)
          - ROUND(TRY_CONVERT(int, s.OnHandUnits) * p.UnitCost, 2)) > 0.01;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Inventory', 'Snapshot dates are all Mondays', '0 errors',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'Confirms inventory shares the weekly demand grid, so the two facts can be joined on week.'
FROM dbo.FactInventorySnapshot
WHERE (DATEDIFF(day, '1900-01-01', SnapshotDate) % 7) <> 0;

/*=============================================================================
  SECTION 9 - Weekly demand
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Weekly demand', 'WeekStart values are all Mondays', '0 errors',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.FactWeeklyDemand
WHERE (DATEDIFF(day, '1900-01-01', WeekStart) % 7) <> 0;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Weekly demand', 'Complete dense grid', '105 x 500 x 6 = 315000',
       CONCAT(COUNT(DISTINCT WeekStart), ' x ', COUNT(DISTINCT ProductID), ' x ',
              COUNT(DISTINCT WarehouseID), ' = ', COUNT(*)),
       CASE WHEN COUNT(*) = COUNT(DISTINCT WeekStart) * COUNT(DISTINCT ProductID)
                            * COUNT(DISTINCT WarehouseID)
            THEN 'PASS' ELSE 'FAIL' END,
       N'A dense grid means forecasting needs no gap-filling before modelling.'
FROM dbo.FactWeeklyDemand;

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Weekly demand', 'Baseline benchmark preserved unchanged', 'WAPE 13.04%',
       CONCAT('WAPE ', FORMAT(SUM(ABS(CAST(BaselineForecastUnits AS decimal(18,4))
                                      - ActualDemandUnits))
                              / NULLIF(SUM(CAST(ActualDemandUnits AS decimal(18,4))), 0),
                              'P2')),
       CASE WHEN ABS(SUM(ABS(CAST(BaselineForecastUnits AS decimal(18,4)) - ActualDemandUnits))
                     / NULLIF(SUM(CAST(ActualDemandUnits AS decimal(18,4))), 0)
                     - 0.1304) < 0.0005
            THEN 'PASS' ELSE 'FAIL' END,
       N'Re-derived in SQL to prove the Phase 14 benchmark survived the load untouched.'
FROM dbo.FactWeeklyDemand;

/*=============================================================================
  SECTION 10 - Product coverage
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Product coverage', 'HasDemandSignal split', '500 with / 500 without',
       CONCAT(SUM(CAST(HasDemandSignal AS int)), ' with / ',
              SUM(1 - CAST(HasDemandSignal AS int)), ' without'),
       CASE WHEN SUM(CAST(HasDemandSignal AS int)) = 500 THEN 'PASS' ELSE 'FAIL' END,
       N'Half the catalogue has no inventory or demand history. Flagged, not hidden.'
FROM dbo.DimProduct;

/*=============================================================================
  SECTION 11 - Security source
=============================================================================*/
INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status], Note)
SELECT 'Security', 'Warehouse mappings resolve or are the ALL sentinel', '0 invalid',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
       N'The Supply Director row uses the literal ALL rather than a warehouse code.'
FROM dbo.SecurityUserAccess AS s
WHERE s.IsAllWarehouses = 0
  AND NOT EXISTS (SELECT 1 FROM dbo.DimWarehouse w WHERE w.WarehouseID = s.WarehouseID);

INSERT INTO #Results (Section, CheckName, Expected, Actual, [Status])
SELECT 'Security', 'Email addresses normalised to lower case', '0 errors',
       CAST(COUNT(*) AS varchar(20)),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM dbo.SecurityUserAccess
WHERE UserEmail <> LOWER(UserEmail) COLLATE Latin1_General_CS_AS;

/*=============================================================================
  OUTPUT
=============================================================================*/
SELECT Section, CheckName, Expected, Actual, [Status], Note
FROM   #Results
ORDER BY Seq;

SELECT
    Section,
    Checks = COUNT(*),
    Passed = SUM(CASE WHEN [Status] = 'PASS' THEN 1 ELSE 0 END),
    Failed = SUM(CASE WHEN [Status] = 'FAIL' THEN 1 ELSE 0 END)
FROM   #Results
GROUP BY Section
ORDER BY Section;

SELECT
    TotalChecks = COUNT(*),
    Passed      = SUM(CASE WHEN [Status] = 'PASS' THEN 1 ELSE 0 END),
    Failed      = SUM(CASE WHEN [Status] = 'FAIL' THEN 1 ELSE 0 END),
    Verdict     = CASE WHEN SUM(CASE WHEN [Status] = 'FAIL' THEN 1 ELSE 0 END) = 0
                       THEN 'PHASE 3 QUALITY GATE: PASS'
                       ELSE 'PHASE 3 QUALITY GATE: FAIL - see failed checks above'
                  END
FROM #Results;

DROP TABLE IF EXISTS #Results;
DROP TABLE IF EXISTS #Counts;
GO
