"""
05_generate_measure_dictionary.py
=================================
Generates Documentation/dax_measure_dictionary.md directly from the TMDL.

Reading the model rather than transcribing it means the dictionary cannot drift
out of step: re-run after any measure change and it is correct by construction.

Measured validation results are merged in from the reconciliation run when the
evaluation file is available, so the dictionary records what each measure
actually returned rather than what it was expected to return.

Usage
-----
    python Python/05_generate_measure_dictionary.py [path-to-eval-file]
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TMDL = (ROOT / "PowerBI" / "SupplyChainControlTower.SemanticModel" / "definition"
        / "tables" / "_Measures.tmdl")
OUT = ROOT / "Documentation" / "dax_measure_dictionary.md"
DEFAULT_EVAL = Path(os.environ.get("TEMP", "/tmp")) / "phase6_eval.txt"

FOLDER_NOTES = {
    "01 Core KPIs": "Headline figures for executive pages.",
    "02 Sales": "Sales-order detail beyond the headline numbers.",
    "03 Inventory & Demand": "Semi-additive stock position and demand baselines.",
    "04 Procurement": "Purchase-order activity and supplier lead time.",
    "05 Logistics": "Outbound shipment and freight measures.",
    "06 Delivery Performance": "On-time performance for deliveries and receipts. Completed records only.",
    "07 Date Roles": "Demonstrations of the inactive date relationships via USERELATIONSHIP.",
    "08 Model Controls": "Central configuration read from the disconnected ModelConfig table.",
}


def parse_measures(path: Path) -> list[dict]:
    txt = path.read_text(encoding="utf-8")
    measures = []
    # Each measure block starts at a tab-indented `measure` line; an optional
    # `///` description line precedes it.
    blocks = re.split(r"\n\tmeasure ", txt)
    preamble = blocks[0]
    for i, block in enumerate(blocks[1:], start=1):
        header = block.split("\n")[0]
        name = header.split("=")[0].strip().strip("'")
        # Expression: everything between the `=` and the first property line.
        expr_match = re.search(r"=\s*\n?(.*?)(?=\n\t\t(?:formatString|displayFolder|lineageTag):)",
                               block, re.S)
        expr = expr_match.group(1) if expr_match else header.split("=", 1)[-1]
        expr = "\n".join(l.strip() for l in expr.strip().splitlines() if l.strip())
        fmt = (re.search(r"formatString: (.+)", block) or [None, ""])[1].strip()
        folder = (re.search(r"displayFolder: (.+)", block) or [None, ""])[1].strip()
        # The description is the /// line at the end of the PREVIOUS block.
        prev = preamble if i == 1 else blocks[i - 1]
        desc_lines = [l.strip().lstrip("/").strip()
                      for l in prev.splitlines() if l.strip().startswith("///")]
        desc = desc_lines[-1] if desc_lines else ""
        measures.append({"name": name, "expr": expr, "format": fmt,
                         "folder": folder, "description": desc})
    return measures


def parse_eval(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split("|", 2)
        if len(parts) == 3 and parts[0] == "GLOBAL":
            out[parts[1]] = parts[2]
    return out


def fmt_value(v: str) -> str:
    try:
        f = float(v)
        return f"{f:,.4f}".rstrip("0").rstrip(".") if "." in f"{f}" else f"{int(f):,}"
    except (TypeError, ValueError):
        return v


def main() -> int:
    if not TMDL.exists():
        print(f"_Measures.tmdl not found: {TMDL}", file=sys.stderr)
        return 1

    eval_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_EVAL
    measured = parse_eval(eval_path)
    measures = parse_measures(TMDL)

    lines = [
        "# DAX Measure Dictionary",
        "",
        "**Project:** Enterprise Supply Chain Control Tower  ",
        "**Generated by:** `Python/05_generate_measure_dictionary.py` from the TMDL  ",
        f"**Measures:** {len(measures)}",
        "",
        "> Generated from the model rather than written by hand, so it cannot drift",
        "> out of step with the measures it documents. Re-run after any change.",
        "",
        "## Conventions",
        "",
        "- Every measure lives in `_Measures`. None sit on fact tables.",
        "- `DIVIDE()` is used wherever a denominator could be zero or blank.",
        "- The as-of date is read from `ModelConfig`. `TODAY()` is never used for business logic.",
        "- Money is formatted `#,0.00` without a currency symbol: the source states no currency.",
        "- **There is no OTIF measure.** The dataset records no delivered or received quantity, so \"in full\" cannot be demonstrated. On-time performance is exposed under its own name.",
        "",
    ]

    if measured:
        lines += [
            "## Validation",
            "",
            "The **Measured** column holds the value each measure actually returned",
            "against the live model with no filters applied. Every figure with a SQL",
            "equivalent was reconciled against an independently written query —",
            "**73 checks, 73 passed**. See `Python/04_reconcile_measures.py`.",
            "",
        ]

    for folder in sorted({m["folder"] for m in measures}):
        lines += ["---", "", f"## {folder}", ""]
        if folder in FOLDER_NOTES:
            lines += [FOLDER_NOTES[folder], ""]
        for m in sorted([x for x in measures if x["folder"] == folder],
                        key=lambda x: x["name"]):
            lines.append(f"### {m['name']}")
            lines.append("")
            if m["description"]:
                lines.append(m["description"])
                lines.append("")
            meta = [f"**Format:** `{m['format']}`"]
            if m["name"] in measured:
                meta.append(f"**Measured (unfiltered):** `{fmt_value(measured[m['name']])}`")
            lines.append(" · ".join(meta))
            lines.append("")
            lines.append("```dax")
            lines.append(m["expr"])
            lines.append("```")
            lines.append("")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} — {len(measures)} measures across "
          f"{len({m['folder'] for m in measures})} folders")
    if measured:
        print(f"Merged measured values for {len(measured)} measures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
