# -*- coding: utf-8 -*-
"""
Generates Documentation/dax_measure_dictionary.md from the measure specification
(Python/model_measures.py), merged with the grand-total value of every measure as
measured in the live model by Validation/reconcile_measures.ps1
(Validation/measure_values.csv). Values are never typed by hand.

Usage:  python Python/03_generate_measure_dictionary.py
"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "Python"))
from model_measures import CALC_GROUPS, MEASURES  # noqa: E402

OUT = ROOT / "Documentation" / "dax_measure_dictionary.md"
VALUES = ROOT / "Validation" / "measure_values.csv"


def fmt_value(raw, fmt):
    if raw in (None, ""):
        return "(blank)"
    try:
        v = float(raw)
    except ValueError:
        return raw
    if fmt and "%" in fmt:
        return f"{v:.2%}"
    if fmt and "$" in fmt:
        return f"${v:,.2f}" if abs(v) < 1000 else f"${v:,.0f}"
    if v.is_integer():
        return f"{int(v):,}"
    return f"{v:,.4f}"


def main():
    values = {}
    if VALUES.exists():
        with VALUES.open(encoding="utf-8-sig") as f:
            values = {r["Measure"]: r["Value"] for r in csv.DictReader(f)}

    folders = {}
    for m in MEASURES:
        folders.setdefault(m["folder"], []).append(m)

    L = ["# DAX Measure Dictionary - SaaS Revenue, Retention & Churn", "",
         "Generated by `Python/03_generate_measure_dictionary.py` from `Python/model_measures.py`. "
         "**Value (all data)** is each measure at the grand total - nothing selected - measured in the live "
         "Power BI model by `Validation/reconcile_measures.ps1`, not typed by hand.", "",
         "Reading the values: with no date selected, a STOCK (MRR, ARR, customers, seats) is read at the as-of "
         "date, 31 Aug 2026, and a FLOW (new business, churn, invoices, tickets) covers the whole period, Jan 2022 "
         "to Aug 2026. Amounts are USD. Two measures - lifetime value and CAC payback - depend on a gross-margin "
         "ASSUMPTION held in ModelConfig, and say so. The data is synthetic.", "",
         f"**{len(MEASURES)} measures in {len(folders)} folders, plus {len(CALC_GROUPS)} calculation groups "
         f"({sum(len(g['items']) for g in CALC_GROUPS)} items).**", ""]

    L += ["## Calculation groups", "",
          "A calculation group applies to the measure a visual already shows, so a comparison is one selection "
          "rather than six copies of every measure.", ""]
    for g in CALC_GROUPS:
        L += [f"### {g['name']} (precedence {g['precedence']})", "", g["desc"], "",
              "| Item | Does |", "|---|---|"]
        for item, desc, _dax, _fmt in g["items"]:
            L.append(f"| {item} | {desc} |")
        L.append("")
        for item, _desc, dax, fmt in g["items"]:
            L += [f"<details><summary><code>{g['name']} / {item}</code></summary>", "", "```dax", dax.strip("\n"), "```"]
            if fmt:
                L += ["", "Format string definition:", "", "```dax", " ".join(fmt.split()), "```"]
            L += ["", "</details>", ""]

    for folder, ms in folders.items():
        L += [f"## {folder}", "", "| Measure | Value (all data) | Description |", "|---|---|---|"]
        for m in ms:
            hidden = " *(hidden)*" if m["hidden"] else ""
            L.append(f"| {m['name']}{hidden} | {fmt_value(values.get(m['name']), m['fmt'])} | {m['desc']} |")
        L.append("")
        for m in ms:
            L += [f"<details><summary><code>{m['name']}</code></summary>", "", "```dax", m["dax"].strip("\n"), "```",
                  "", "</details>", ""]
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(MEASURES)} measures, "
          f"{sum(1 for m in MEASURES if m['name'] in values)} with measured values, "
          f"{len(CALC_GROUPS)} calculation groups")


if __name__ == "__main__":
    main()
